/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;

import javax.swing.JOptionPane;
import pojos.LecturaDeArchivos;


/**
 *
 * @author egarduno
 */
public class InterfazLecturaDeArchivos extends javax.swing.JFrame {
    
    private FrameEstudiante ventanaEstudiante;
    private LecturaDeArchivos lecturaDeArchivos;
    

    /** Creates new form InterfazLecturaDeArchivos */
    public InterfazLecturaDeArchivos() {
        initComponents();
        lecturaDeArchivos = new LecturaDeArchivos();
        ventanaEstudiante = new FrameEstudiante(this);
        Escritorio.add(ventanaEstudiante);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        MenuPrincipal = new javax.swing.JMenu();
        SubMenuGuardarEstudiante = new javax.swing.JMenuItem();
        Ver = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        MenuPrincipal.setText("Menu Principal");

        SubMenuGuardarEstudiante.setText("Estudiante");
        SubMenuGuardarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuGuardarEstudianteActionPerformed(evt);
            }
        });
        MenuPrincipal.add(SubMenuGuardarEstudiante);

        MenuBar.add(MenuPrincipal);

        Ver.setText("Ver");
        MenuBar.add(Ver);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuGuardarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuGuardarEstudianteActionPerformed
        ventanaEstudiante.show();
    }//GEN-LAST:event_SubMenuGuardarEstudianteActionPerformed

    public void registrarEstudiante(String nombre, String matricula, String  semestre)
    {
        boolean condicionesValidas = true;
        
        if( nombre.equals( "" ) || matricula.equals( "" ) || semestre.equals( "" ))
        {
            condicionesValidas = false;
            JOptionPane.showMessageDialog( this, "Debe llenar todos los campos! ", "Error", JOptionPane.ERROR_MESSAGE );
        }
        
        lecturaDeArchivos.registrarEstudiante(nombre, matricula, semestre);
        
    }
    
    public void mostrarEstudiantes()
    {
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLecturaDeArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLecturaDeArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLecturaDeArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLecturaDeArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLecturaDeArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuPrincipal;
    private javax.swing.JMenuItem SubMenuGuardarEstudiante;
    private javax.swing.JMenu Ver;
    // End of variables declaration//GEN-END:variables

}
